# SwiftLint設定ファイル

# 無効化するルール
disabled_rules:
  - trailing_whitespace

# 有効化するオプトインルール
opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - sorted_imports
  - unused_optional_binding
  - static_over_final_class

# 除外するパス
excluded:
  - HandEst/Preview Content
  - .build
  - DerivedData
  - .swiftpm

# カスタムルール設定
identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id

# ファイルの長さ
file_length:
  warning: 500
  error: 1200

# 型の本体の長さ
type_body_length:
  warning: 300
  error: 500

# 関数の本体の長さ
function_body_length:
  warning: 40
  error: 100

# 行の長さ
line_length:
  warning: 120
  error: 200