# SwiftLint Configuration for HandEst

# 除外するフォルダ
excluded:
  - .build
  - Package.swift
  - HandEst.xcodeproj
  - HandEst/Preview Content
  - HandEst/Assets.xcassets
  - Scripts/

# 有効にするルール
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - yoda_condition

# 無効にするルール
disabled_rules:
  - todo # TODOコメントを許可
  - trailing_whitespace # 末尾空白を一時的に許可
  - trailing_newline # 末尾改行を一時的に許可
  - trailing_closure # トレイリングクロージャを一時的に許可

# カスタム設定
line_length:
  warning: 120
  error: 150

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 6
  function_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

# ファイルヘッダー設定（必要に応じて有効化）
# file_header:
#   required_pattern: |
#                     \/\/
#                     \/\/  .*\.swift
#                     \/\/  HandEst
#                     \/\/
#                     \/\/  Created by .* on \d{4}\/\d{2}\/\d{2}\.
#                     \/\/

# カスタムルール
custom_rules:
  # 日本語コメントの推奨
  japanese_comments:
    name: "Japanese Comments"
    message: "日本語でのコメントを推奨します"
    regex: '\/\/\s*[a-zA-Z]{20,}'
    severity: warning
  
  # AppLoggerの使用を推奨
  print_statement:
    name: "Print Statement"
    message: "print文の代わりにAppLoggerを使用してください"
    regex: '\bprint\s*\('
    severity: warning
  
  # TODO/FIXMEに日本語使用を推奨
  todo_fixme_japanese:
    name: "TODO/FIXME Japanese"
    message: "TODO/FIXMEは日本語で記述してください"
    regex: '(TODO|FIXME):\s*[a-zA-Z]'
    severity: warning

# レポート形式
reporter: "xcode"