# SwiftLint Configuration for HandEst

# 除外するフォルダ
excluded:
  - .build
  - Package.swift
  - HandEst.xcodeproj
  - HandEst/Preview Content
  - HandEst/Assets.xcassets
  - Scripts/
  - LocalPackages/

# 有効にするルール（開発効率重視で最小限）
opt_in_rules:
  - array_init
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - last_where
  - legacy_random
  - redundant_nil_coalescing
  - toggle_bool
  - yoda_condition

# アナライザールール
analyzer_rules:
  - unused_import

# 無効にするルール（開発効率重視）
disabled_rules:
  - todo # TODOコメントを許可
  - trailing_whitespace # 末尾空白を許可
  - trailing_newline # 末尾改行を許可
  - trailing_closure # トレイリングクロージャを許可
  - line_length # LLM可読性のため行長制限を無効化
  - attributes # 属性の配置ルールを無効化
  - number_separator # 数値セパレータルールを無効化
  - identifier_name # 識別子名ルールを緩和
  - type_body_length # 型本体長制限を緩和
  - function_body_length # 関数本体長制限を緩和
  - vertical_parameter_alignment_on_call # パラメータ整列を無効化
  - closure_end_indentation # クロージャインデントを無効化
  - multiple_closures_with_trailing_closure # TCAテストでよく使用される
  - redundant_optional_initialization # nilの明示的初期化を許可
  - cyclomatic_complexity # 複雑度チェックを無効化
  - large_tuple # 大きなタプルを許可

# カスタム設定

file_length:
  warning: 500
  error: 800

nesting:
  type_level:
    warning: 3
    error: 6
  function_level:
    warning: 5
    error: 10

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

# ファイルヘッダー設定（必要に応じて有効化）
# file_header:
#   required_pattern: |
#                     \/\/
#                     \/\/  .*\.swift
#                     \/\/  HandEst
#                     \/\/
#                     \/\/  Created by .* on \d{4}\/\d{2}\/\d{2}\.
#                     \/\/

# カスタムルール（開発効率重視で最小限）
custom_rules:
  # AppLoggerの使用を推奨（重要なもののみ）
  print_statement:
    name: "Print Statement"
    message: "print文の代わりにAppLoggerを使用してください"
    regex: '\bprint\s*\('
    severity: warning

# レポート形式
reporter: "xcode"