name: HandEst
options:
  bundleIdPrefix: com.sagawafumiya
  deploymentTarget:
    iOS: 18.2
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true
  fileTypes:
    # .mdファイルをリソースとして扱う
    .md:
      buildPhase: resources

settings:
  base:
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1

targets:
  HandEst:
    type: application
    platform: iOS
    sources:
      - path: HandEst
        createIntermediateGroups: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sagawafumiya.HandEst
        DEVELOPMENT_TEAM: 8BD446AR8T
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: HandEst
        INFOPLIST_KEY_CFBundleName: HandEst
        INFOPLIST_KEY_CFBundleShortVersionString: 1.0
        INFOPLIST_KEY_CFBundleVersion: 1
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    dependencies:
      - package: ComposableArchitecture
        product: ComposableArchitecture
    preBuildScripts:
      - script: |
          if [ -f /opt/homebrew/bin/swiftlint ]; then
            /opt/homebrew/bin/swiftlint
          elif [ -f /usr/local/bin/swiftlint ]; then
            /usr/local/bin/swiftlint
          elif which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        name: SwiftLint
        inputFiles:
          - $(SRCROOT)/HandEst
        outputFiles:
          - $(DERIVED_FILE_DIR)/swiftlint.txt
        basedOnDependencyAnalysis: true

  HandEstTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - HandEstTests
    dependencies:
      - target: HandEst
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sagawafumiya.HandEstTests
        DEVELOPMENT_TEAM: 8BD446AR8T
        GENERATE_INFOPLIST_FILE: YES
    scheme:
      testTargets:
        - HandEstTests
      parallelizeBuildables: true
      buildImplicitDependencies: true

  HandEstUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - HandEstUITests
    dependencies:
      - target: HandEst
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sagawafumiya.HandEstUITests
        DEVELOPMENT_TEAM: 8BD446AR8T
        TEST_TARGET_NAME: HandEst
        GENERATE_INFOPLIST_FILE: YES

schemes:
  HandEst:
    build:
      targets:
        HandEst: all
    test:
      targets:
        - HandEstTests
        - HandEstUITests
      parallelizeBuildables: true
      buildImplicitDependencies: true
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 1.0.0